Algoritmo "medidas"

Var
   a, b, c, areaQuadrado, areaTriangulo, areaTrapezio : real



Inicio
  escreva("Digite o lado A: ")
  leia(a)
  escreva("Digite o lado B: ")
  leia(b)
  escreva("Digite o lado C: ")
  leia(c)
  areaQuadrado <- a * a
  areaTriangulo <- a * b / 2
  areaTrapezio <- (a + b) * c /2
  escreval("Area do quadrado:",areaQuadrado:8:4)
  escreval("Area do triangulo:",areaTriangulo:8:4)
  escreval("Area do trapezio:",areaTrapezio:8:4)





Fimalgoritmo